4:TDD/BDD 1.0
Savelov-Vitaliy/qna pull request #1
Opened 2019-01-29 20:48 UTC by Savelov-Vitaliy

2019-01-30 08:41 UTC, vkurennov requested changes

2019-01-30 08:41 UTC, vkurennov commented on app/models/answer.rb
> +  validates :title, :body, :question_id, presence: true
1. question_id не нужно валидировать, в rails 5+ валидации для полей belongs_to происходят автоматически
2. Зачем ответу заголовок? Достаточно только тела

2019-01-30 08:41 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  it { should belong_to :question }
В тестах, как и в самих моделей принят порядок "сначала ассоцаиции, потом валидации"

2019-01-30 08:41 UTC, vkurennov commented on spec/models/question_spec.rb
> +  it { should have_many :answers }
опцию dependent тоже надо тестировать, shoulda-matchers это умеет

2019-01-30 17:18 UTC, Savelov-Vitaliy commented on spec/models/answer_spec.rb
> +  it { should belong_to :question }
Ох, точно! об этом же говорили в уроке

2019-01-31 07:57 UTC, vkurennov approved these changes

2019-01-31 08:49 UTC, merged