5 controller tests
Savelov-Vitaliy/qna pull request #2
Opened 2019-02-02 21:46 UTC by Savelov-Vitaliy

2019-02-03 10:37 UTC, vkurennov requested changes

2019-02-03 10:37 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:question_id, :body)
question_id приходит в url и доступен через обычный params, он не входит  в список параметров формы, поэтому здесь его быть не должно

2019-02-03 10:37 UTC, vkurennov commented on config/routes.rb
> +    resources :answers
рекомендую сразу объявить ресурс как  shallow, потом будет проще.

2019-02-03 10:37 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
связь с вопросом должна устанавливаться через ассоциации вопроса, а не через параметры. Через параметры - не безопсано (можно подемнить параметр) и сам question_id в реальности не будет приходить в форме, он будет в url

2019-02-03 10:37 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, question_id: question) } }.to change(Answer, :count).by(1)
1. тут надо проверить, что ответ связывается с вопросом. можно прямо в change через ассоциации вопроса
2. question_id должен передаваться только в params, а не в answer (здесь и далее во всех тестах)

2019-02-03 19:15 UTC, Savelov-Vitaliy commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:question_id, :body)
это понятно. Непонятно, почему когда я question_id убераю из permit - падают тесты:
"AnswersController POST #create with valid attributes saves a new answer in the database" и 
"AnswersController POST #create with valid attributes saves a new answer in the database"

Впечатление что связь не работает

2019-02-03 20:17 UTC, Savelov-Vitaliy commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
начинаю забывать Rails.часть2 :))

2019-02-03 20:28 UTC, Savelov-Vitaliy commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, question_id: question) } }.to change(Answer, :count).by(1)
1. в тестах модели есть уже проверка на то что ответ связывается с вопросом.

2019-02-04 09:10 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, question_id: question) } }.to change(Answer, :count).by(1)
Ну так это в моделях. А в контроллере можно написать код, который создаст модель без связи с вопросом (для этого извернуться надо, но это возможно). Вот и мы должны протестировать, что этого не происходит и все связи устанавливаеются как надо.

2019-02-04 09:11 UTC, vkurennov approved these changes

2019-02-05 11:04 UTC, merged