6 acceptance tests
Savelov-Vitaliy/qna pull request #3
Opened 2019-02-16 20:13 UTC by Savelov-Vitaliy

2019-02-17 08:50 UTC, vkurennov requested changes

2019-02-17 08:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, except: %i[index show]
ни show ни index  для ответов не нужны, поэтому и в except их указывать нет смысла

2019-02-17 08:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if answer.author? current_user
Для всех методов, кроме тех, что представляют DSL (типа хелперов в видах и максросов валидаций и ассоциаций), заключай аргументы в скобки - это улучшает читаемость

2019-02-17 08:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(id: question)
`redirect_to question`

2019-02-17 08:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render :show
нам не нужен show для ответа, ведь все ответы располагаются на странице вопроса. Поэтому и рендерить надо страницу вопроса. А в данном случае, можно и редирект сделать.

2019-02-17 08:50 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  # expose :answers, -> { question.answers }
удаляй закомментированный код, нечего хранить мусор в репозитории

2019-02-17 08:50 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @answer ||= question.answers.new(user_id: current_user&.id)
работай с ассоциациями, а не с id, в данном случае можно записать как `new(user: current_user)`

2019-02-17 08:50 UTC, vkurennov commented on app/models/answer.rb
> +    author == user
Сравнивать стоит по id, иначе у тебя тут будет лишний запрос на ассоциацию и в итоге это приведет к проблеме n+1 запроса. Т.е. сравниваем по id, присваиваем по объектам и ассоциациям. У тебя ровно наоборот получилось везде.

2019-02-17 08:50 UTC, vkurennov commented on app/models/question.rb
> +  def author?(user)
Дублирование. Не  лучше ли перенести этот метод в класс User и у юзера "спрашивать" является ли он автором того или иного объекта. И вообще, когда ты пишешь одинаковый код, это должно стать сигналом, что либо есть другое решение и его можно применить сразу, либо это нужно отрефакторить чуть позже

2019-02-17 08:50 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +-answers.each do |answer|
Вспомни тему про анонимные паршалы из базовой части. Если у тебя есть паршл answers/_answer, то он должен представлять **одиночный** объект. И тогда даже цикл не надо будет писать, достаточно методу render передать коллекцию и он отрендерит для каждого объекта в коллекции нужный паршл.

2019-02-17 08:50 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  li #{answer.id}) #{answer.body}
Не думаю, что id ответа важная информация. Это внутренние данные, пользователь не должен их видеть. Надо думать об UX хотя бы 5-10% времени на разработку.

2019-02-17 08:50 UTC, vkurennov commented on app/views/answers/index.html.slim
> +  = render 'answer', answers: question.answers
в итоге, если сделать как я выше написал (про паршл для одного ответа) все сведется к 
`render question.answers`

2019-02-17 08:50 UTC, vkurennov commented on app/views/answers/show.html.slim
> +p= answer.body
Избавсья от этого вида. Все ответы должны быть на странице вопроса, поэтому index и show для ответов не нужны.

2019-02-17 08:50 UTC, vkurennov commented on app/views/answers/show.html.slim
> +  = f.hidden_field id: answer.id
Удаление через форму - это, конечно, жуткий костыль. Чем тебя ссылка с `method: :delete` не устроила?

2019-02-17 08:50 UTC, vkurennov commented on app/views/answers/show.html.slim
> +/= link_to 'Delete answer', answer_path, method: :delete, data: { confirm: 'Delete this answer?' }
Ну вот же верное направление было, только путь не полный (объект же надо передать в url-хелпер, это же путь к конкретному ответу с конкретным id). Ну и confirm неполный сделал.

Только зачем показывать ссылку всем? Показывай ее только автору

2019-02-17 08:50 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +-questions.each do |question|
Те же замечания, что и для ответа: это должен быть паршл одиночного вопроса

2019-02-17 08:50 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +  li #{question.id}) #{question.title}
А как по этому тексту перейти на страницу самого вопроса? Тесты - это важно и нужно, но это не отменяет и ручного тестирования в браузере. Ты попробуй попользоваться своим прилоежнием как обычный юзер, посмотри, им вообще можно воспользоваться нормально, не вбивая url в адресную строку руками? Удобно ли им пользоваться?

2019-02-17 08:50 UTC, vkurennov commented on app/views/questions/show.html.slim
> +/= link_to 'Delete question', question_path, method: :delete, data: { confirm: 'Delete this question?' }
Удаление должно быть ссылкой, а не формой. И показывай ее только автору

2019-02-17 08:50 UTC, vkurennov commented on app/views/questions/show.html.slim
> +
Согласно заданию, здесь должен быть список ответов

2019-02-17 08:50 UTC, vkurennov commented on app/views/questions/show.html.slim
> += render 'shared/errors', resource: answer
Ошибки лучше ближе к форме выводить

2019-02-17 08:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Тут также должен быть тест, проверяющий ассоциацию с залогиненным юзером

2019-02-17 08:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, :invalid) } }.to_not change(question.answers, :count)
здесь зря исправил. Тут в change должен быть именно Answer, т.к.важно проверить, что в принципе не создан ответ, вне зависимости от его связей

2019-02-17 08:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
У тебя в экшене условие. Значит, надо тестировать все варианты: и когда условие выполнилось и когда не выполнилось. Поэтому тут должно быть 2 контекста: для автора и для не-автора

2019-02-17 08:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
тут надо проверить, что вопрос связвается с залогиненным юзером

2019-02-17 08:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    describe 'DELETE #destroy' do
тут должно быть 2 контекста: для автора и для не-автора

2019-02-17 08:50 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +      visit question_path(id: question)
да зачем ты id передаешь? посмотри в скринкасте, там где-то есть указание id в url-хелперах? достаточно передать просто объект

2019-02-17 08:50 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +      expect(page).to have_content 'Give your answer'
тут надо проверить, что система вывела ошибки валидации

2019-02-17 08:50 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +      expect(page).to have_no_content answer.body
Надо проверить, что перед удалением этот контент на странице есть

2019-02-17 08:50 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +      visit answer_path(id: answer)
удаление должно просиходить со страницы вопроса, там же должен быть список ответов

2019-02-17 08:50 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +      click_on 'Delete answer'
лучше просто не показывать ссылку на удаление не-автору

2019-02-17 08:50 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +    click_on 'Delete answer'
лучше просто не показывать ссылку на удаление не-автору

2019-02-17 08:50 UTC, vkurennov commented on spec/features/question/create_spec.rb
> +    scenario 'asks a question with errors' do
вот видишь как мы в скринкасте писали сценарий. почему же для ответов другая логика? сценарий-то аналогичный. Вообще, старайся проводить чуть больше аналогий между тем, что делается в скринкасте и тем, что надо сделать. Ведь в скринкастах я стараюсь показать и объяснить общие принципы, а не решение конкретной задачи.

2019-02-17 08:50 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +      click_on 'Delete question'
тут тоже перед удалением надо проверить, что вопрос есть на странице

2019-02-17 08:50 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +      click_on 'Delete question'
лучше просто не показывать ссылку на удаление не-автору

2019-02-17 08:50 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +    click_on 'Delete question'
лучше просто не показывать ссылку на удаление не-автору

2019-02-17 08:50 UTC, vkurennov commented on spec/features/question/index_spec.rb
> +  after do
Плохое решение. В блоке after не стоит делать проверок, он нужен, чтобы очистить данные. В тестах, порой, лучше продублировать код, чтобы сценарии читались четко и ясно.

2019-02-17 08:50 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +  after do
Опять же - не нужен здесь after

2019-02-17 08:50 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    question.answers.map { |answer| expect(page).to have_content answer.body }
здесь нужен each, а не map

2019-02-17 08:50 UTC, vkurennov commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
Ничего, что у тебя в моделях есть методы, а тестов на них нет? Любой код, который ты пишешь в моделях, котнтроллерах и других классах, должен быть покрыт тестами. по идее, когда ты хочешь написать какой-то код, ты должен остановиться и начать с тестов, чтобы описать, как будет работать этот код.

2019-02-18 17:11 UTC, Savelov-Vitaliy commented on app/models/answer.rb
> +    author == user
понял. ок

2019-02-18 17:12 UTC, Savelov-Vitaliy commented on app/models/question.rb
> +  def author?(user)
"у юзера "спрашивать" является ли он автором ... объекта" - отличная идея!

2019-02-18 17:14 UTC, Savelov-Vitaliy commented on app/views/answers/_answer.html.slim
> +-answers.each do |answer|
да, точно!

2019-02-18 17:16 UTC, Savelov-Vitaliy commented on app/views/answers/_answer.html.slim
> +  li #{answer.id}) #{answer.body}
id я показываю для себя (когда вручную проверяю работоспособность в браузере, иногда  нужно знать id)

2019-02-18 17:17 UTC, Savelov-Vitaliy commented on app/views/answers/_answer.html.slim
> +  li #{answer.id}) #{answer.body}
то что Id посетителю не нужно показывать - это конечно, согласен

2019-02-18 17:18 UTC, Savelov-Vitaliy commented on app/views/answers/show.html.slim
> +p= answer.body
ок

2019-02-18 17:22 UTC, Savelov-Vitaliy commented on app/views/answers/show.html.slim
> +  = f.hidden_field id: answer.id
предложил оба варианта :)) 
Я где то читал что, синтаксически корректное (валидное) и кроссбраузненое решение - заключить кнопку в форму. И потом, ссылку разве можно ввиде кнопки показать?

2019-02-18 17:24 UTC, Savelov-Vitaliy commented on app/views/answers/show.html.slim
> +/= link_to 'Delete answer', answer_path, method: :delete, data: { confirm: 'Delete this answer?' }
Показывать ссылку только автору - да, отлично!

2019-02-18 17:25 UTC, Savelov-Vitaliy commented on app/views/questions/_question.html.slim
> +  li #{question.id}) #{question.title}
ок

2019-02-18 17:27 UTC, Savelov-Vitaliy commented on app/views/questions/show.html.slim
> +
из задания: "просматривать вопрос и ответы к нему" - не очевидно что это надо на странице вопроса. 
ОК, переделаю

2019-02-18 17:28 UTC, Savelov-Vitaliy commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, :invalid) } }.to_not change(question.answers, :count)
мм, да, точно!

2019-02-19 18:47 UTC, Savelov-Vitaliy commented on app/views/answers/_answer.html.slim
> +-answers.each do |answer|
повторенье - мать ученья :))

2019-02-19 18:58 UTC, Savelov-Vitaliy commented on app/views/answers/show.html.slim
> +/= link_to 'Delete answer', answer_path, method: :delete, data: { confirm: 'Delete this answer?' }
не понял, что значит "confirm неполный"? 
в доках ничего об этом не говорят: https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to

2019-02-19 19:55 UTC, Savelov-Vitaliy commented on spec/features/question/show_spec.rb
> +    question.answers.map { |answer| expect(page).to have_content answer.body }
почему?

2019-02-23 12:13 UTC, Savelov-Vitaliy commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
не смог придумать ничего оригинальнее, чем просто продублировать тест, но вместо question.answers сделать question.author.answers

2019-02-23 12:31 UTC, Savelov-Vitaliy commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
так вышло..

2019-02-24 09:02 UTC, vkurennov requested changes

2019-02-24 09:02 UTC, vkurennov commented on app/models/user.rb
> +    (questions.ids.include?(obj.id) & (obj.class == Question)) ||
1. Зачем ограничивать метод двумя классами? Потом появятся другие сущности, придется метод менять, а ведь суть его при этом не меняется.
2. Поиск по всем id очень не эффективный. Сначала ты в память загружаешь id всех объектов (а их могут быть миллионы), потому по этой коллекции в памяти же проходишь последовательно (через include). Есть гораздо более простой и эффективный способ сравнения без лишних запросов к базе.
3. Операция & -  это пересечение массивов, а не логическое "и" (которое &&), так что тут еще и баг в коде.

2019-02-24 09:02 UTC, vkurennov commented on spec/features/answer/destroy_spec.rb
> +      expect(page).not_to have_css('li', text: "#{answer.body} Delete answer")
лучше проверять через `have_link`

2019-02-24 09:02 UTC, vkurennov commented on spec/features/question/destroy_spec.rb
> +      expect(page).to have_no_content 'Delete question'
тут тоже лучше have_link (have_no_link)

2019-02-24 09:02 UTC, vkurennov commented on spec/features/question/index_spec.rb
> +    questions.map { |question| expect(page).to have_content question.title }
почему map? map используется чтобы преобразовать одну коллекцию в другую, т.е. предполагается, что результат map будет использоваться дальше. А если нужна обычная итерация, то тут each надо использовать

2019-02-25 09:50 UTC, vkurennov requested changes

2019-02-25 09:50 UTC, vkurennov commented on app/models/user.rb
> +    id == obj.try(:author)&.id
Ты по-прежнему делаешь запрос к базе, что приведет к проблеме  n+1 запроса. Но ведь ты сравниваешь по id, а у объекта уже есть поле с id ассоциации. Так обратись напрямую к полю, а не к ассоциации и тогда лишнего запроса не будет

2019-02-25 09:50 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'is the questions author' do
Используй динамические матчеры - они смотрятся гораздо лучше:

`expect(question.author).to be_author_of(question)`

2019-02-25 09:50 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'is the answers author' do
У тебя метод универсальный теперь и не зависит от типа аргумента, поэтому достаточно протестировать на одном любом объекте

2019-02-25 13:37 UTC, Savelov-Vitaliy commented on app/models/user.rb
> +    id == obj.try(:author)&.id
🤦‍♂️

2019-02-25 14:35 UTC, vkurennov approved these changes

2019-02-25 14:35 UTC, vkurennov commented on app/models/user.rb
> +    id == obj.try(:user_id)
здесь лучше использовать `&.` вместо `try`

2019-02-25 15:16 UTC, merged